// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: test.capnp

#include "test.capnp.h"

namespace capnp {
namespace schemas {
static const ::capnp::_::AlignedData<61> b_9ccead15aa33c332 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     50, 195,  51, 170,  21, 173, 206, 156,
     11,   0,   0,   0,   1,   0,   1,   0,
    221, 122, 226,  53, 121,  81, 169, 251,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 130,   0,   0,   0,
     25,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 175,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 101, 115, 116,  46,  99,  97, 112,
    110, 112,  58,  68,  97, 116, 101,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
     12,   0,   0,   0,   3,   0,   4,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   1,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     69,   0,   0,   0,  42,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     64,   0,   0,   0,   3,   0,   1,   0,
     76,   0,   0,   0,   2,   0,   1,   0,
      1,   0,   0,   0,   2,   0,   0,   0,
      0,   0,   1,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     73,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     68,   0,   0,   0,   3,   0,   1,   0,
     80,   0,   0,   0,   2,   0,   1,   0,
      2,   0,   0,   0,   3,   0,   0,   0,
      0,   0,   1,   0,   2,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     77,   0,   0,   0,  34,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     72,   0,   0,   0,   3,   0,   1,   0,
     84,   0,   0,   0,   2,   0,   1,   0,
    121, 101,  97, 114,   0,   0,   0,   0,
      3,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      3,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    109, 111, 110, 116, 104,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    100,  97, 121,   0,   0,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      6,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_9ccead15aa33c332 = b_9ccead15aa33c332.words;
#if !CAPNP_LITE
static const uint16_t m_9ccead15aa33c332[] = {2, 1, 0};
static const uint16_t i_9ccead15aa33c332[] = {0, 1, 2};
const ::capnp::_::RawSchema s_9ccead15aa33c332 = {
  0x9ccead15aa33c332, b_9ccead15aa33c332.words, 61, nullptr, m_9ccead15aa33c332,
  0, 3, i_9ccead15aa33c332, nullptr, nullptr, { &s_9ccead15aa33c332, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<28> b_f5523ae5b3961fb7 = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    183,  31, 150, 179, 229,  58,  82, 245,
     11,   0,   0,   0,   3,   0,   0,   0,
    221, 122, 226,  53, 121,  81, 169, 251,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0, 162,   0,   0,   0,
     29,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     25,   0,   0,   0,  71,   0,   0,   0,
     65,   0,   0,   0,   7,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 101, 115, 116,  46,  99,  97, 112,
    110, 112,  58,  67,  97, 108, 108,  97,
     98, 108, 101,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   1,   0,   1,   0,
      4,   0,   0,   0,   3,   0,   5,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     76, 132,  48, 127,  63, 197,   9, 136,
    139, 172, 205,  47, 205, 134,  69, 203,
     17,   0,   0,   0,  50,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      5,   0,   0,   0,   7,   0,   0,   0,
    112, 114, 105, 110, 116,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   1,   0,
      0,   0,   0,   0,   1,   0,   1,   0, }
};
::capnp::word const* const bp_f5523ae5b3961fb7 = b_f5523ae5b3961fb7.words;
#if !CAPNP_LITE
static const ::capnp::_::RawSchema* const d_f5523ae5b3961fb7[] = {
  &s_8809c53f7f30844c,
  &s_cb4586cd2fcdac8b,
};
static const uint16_t m_f5523ae5b3961fb7[] = {0};
const ::capnp::_::RawSchema s_f5523ae5b3961fb7 = {
  0xf5523ae5b3961fb7, b_f5523ae5b3961fb7.words, 28, d_f5523ae5b3961fb7, m_f5523ae5b3961fb7,
  2, 1, nullptr, nullptr, nullptr, { &s_f5523ae5b3961fb7, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<17> b_8809c53f7f30844c = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
     76, 132,  48, 127,  63, 197,   9, 136,
     20,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  10,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 101, 115, 116,  46,  99,  97, 112,
    110, 112,  58,  67,  97, 108, 108,  97,
     98, 108, 101,  46, 112, 114, 105, 110,
    116,  36,  80,  97, 114,  97, 109, 115,
      0,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_8809c53f7f30844c = b_8809c53f7f30844c.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_8809c53f7f30844c = {
  0x8809c53f7f30844c, b_8809c53f7f30844c.words, 17, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_8809c53f7f30844c, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
static const ::capnp::_::AlignedData<17> b_cb4586cd2fcdac8b = {
  {   0,   0,   0,   0,   5,   0,   6,   0,
    139, 172, 205,  47, 205, 134,  69, 203,
     20,   0,   0,   0,   1,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   7,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
     21,   0,   0,   0,  18,   1,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,   0,   0,
    116, 101, 115, 116,  46,  99,  97, 112,
    110, 112,  58,  67,  97, 108, 108,  97,
     98, 108, 101,  46, 112, 114, 105, 110,
    116,  36,  82, 101, 115, 117, 108, 116,
    115,   0,   0,   0,   0,   0,   0,   0, }
};
::capnp::word const* const bp_cb4586cd2fcdac8b = b_cb4586cd2fcdac8b.words;
#if !CAPNP_LITE
const ::capnp::_::RawSchema s_cb4586cd2fcdac8b = {
  0xcb4586cd2fcdac8b, b_cb4586cd2fcdac8b.words, 17, nullptr, nullptr,
  0, 0, nullptr, nullptr, nullptr, { &s_cb4586cd2fcdac8b, nullptr, nullptr, 0, 0, nullptr }
};
#endif  // !CAPNP_LITE
}  // namespace schemas
}  // namespace capnp

// =======================================================================================


// Date
constexpr uint16_t Date::_capnpPrivate::dataWordSize;
constexpr uint16_t Date::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind Date::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Date::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

#if !CAPNP_LITE
::capnp::Request< ::Callable::PrintParams,  ::Callable::PrintResults>
Callable::Client::printRequest(::kj::Maybe< ::capnp::MessageSize> sizeHint) {
  return newCall< ::Callable::PrintParams,  ::Callable::PrintResults>(
      0xf5523ae5b3961fb7ull, 0, sizeHint);
}
::kj::Promise<void> Callable::Server::print(PrintContext) {
  return ::capnp::Capability::Server::internalUnimplemented(
      "test.capnp:Callable", "print",
      0xf5523ae5b3961fb7ull, 0);
}
::kj::Promise<void> Callable::Server::dispatchCall(
    uint64_t interfaceId, uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (interfaceId) {
    case 0xf5523ae5b3961fb7ull:
      return dispatchCallInternal(methodId, context);
    default:
      return internalUnimplemented("test.capnp:Callable", interfaceId);
  }
}
::kj::Promise<void> Callable::Server::dispatchCallInternal(
    uint16_t methodId,
    ::capnp::CallContext< ::capnp::AnyPointer, ::capnp::AnyPointer> context) {
  switch (methodId) {
    case 0:
      return print(::capnp::Capability::Server::internalGetTypedContext<
           ::Callable::PrintParams,  ::Callable::PrintResults>(context));
    default:
      (void)context;
      return ::capnp::Capability::Server::internalUnimplemented(
          "test.capnp:Callable",
          0xf5523ae5b3961fb7ull, methodId);
  }
}
#endif  // !CAPNP_LITE

// Callable
#if !CAPNP_LITE
constexpr ::capnp::Kind Callable::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Callable::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// Callable::PrintParams
constexpr uint16_t Callable::PrintParams::_capnpPrivate::dataWordSize;
constexpr uint16_t Callable::PrintParams::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind Callable::PrintParams::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Callable::PrintParams::_capnpPrivate::schema;
#endif  // !CAPNP_LITE

// Callable::PrintResults
constexpr uint16_t Callable::PrintResults::_capnpPrivate::dataWordSize;
constexpr uint16_t Callable::PrintResults::_capnpPrivate::pointerCount;
#if !CAPNP_LITE
constexpr ::capnp::Kind Callable::PrintResults::_capnpPrivate::kind;
constexpr ::capnp::_::RawSchema const* Callable::PrintResults::_capnpPrivate::schema;
#endif  // !CAPNP_LITE



